package io.github.prplegryn.katch.web

import android.content.Context
import android.webkit.CookieManager
import android.webkit.WebStorage
import java.io.File
import java.net.HttpCookie
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class CookieExporter(private val context: Context) {
    val cookieFile: File
        get() = File(context.filesDir, "cookies/xiaohongshu-cookies.txt")

    fun hasCookieFile(): Boolean = cookieFile.exists() && cookieFile.length() > 0L

    fun clearCookies() {
        CookieManager.getInstance().removeAllCookies(null)
        CookieManager.getInstance().flush()
        WebStorage.getInstance().deleteAllData()
        cookieFile.delete()
    }

    fun exportForYtDlp(): File {
        CookieManager.getInstance().flush()
        val rows = linkedMapOf<String, CookieRow>()
        COOKIE_URLS.forEach { url ->
            val host = url.substringAfter("://").substringBefore("/")
            val domain = if (host.startsWith("www.")) ".${host.removePrefix("www.")}" else ".$host"
            CookieManager.getInstance().getCookie(url)
                ?.split(';')
                ?.mapNotNull { raw -> raw.trim().takeIf { it.contains("=") } }
                ?.forEach { pair ->
                    val parsed = HttpCookie.parse(pair).firstOrNull() ?: return@forEach
                    val key = "$domain|${parsed.name}"
                    rows[key] = CookieRow(
                        domain = domain,
                        includeSubdomains = true,
                        path = "/",
                        secure = url.startsWith("https://"),
                        expires = "0",
                        name = parsed.name,
                        value = parsed.value,
                    )
                }
        }

        cookieFile.parentFile?.mkdirs()
        cookieFile.writeText(buildString {
            appendLine("# Netscape HTTP Cookie File")
            appendLine("# Generated by Akatcha at ${stamp()}")
            rows.values.forEach { row ->
                appendLine(
                    listOf(
                        row.domain,
                        row.includeSubdomains.toString().uppercase(Locale.US),
                        row.path,
                        row.secure.toString().uppercase(Locale.US),
                        row.expires,
                        row.name,
                        row.value,
                    ).joinToString("\t"),
                )
            }
        })
        return cookieFile
    }

    private fun stamp(): String =
        SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date())

    private data class CookieRow(
        val domain: String,
        val includeSubdomains: Boolean,
        val path: String,
        val secure: Boolean,
        val expires: String,
        val name: String,
        val value: String,
    )

    companion object {
        const val DESKTOP_USER_AGENT =
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
                "(KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"

        const val XIAOHONGSHU_URL = "https://www.xiaohongshu.com"

        private val COOKIE_URLS = listOf(
            "https://www.xiaohongshu.com/",
            "https://xiaohongshu.com/",
            "https://edith.xiaohongshu.com/",
            "https://xhslink.com/",
        )
    }
}
